//
//  SimpleConversationManager.swift
//  Loop
//
//  Created by Ash Bhat on 11/2/24.
//

import Foundation

// MARK: - Simple Models

struct SimpleConversation: Codable {
    let id: String
    var title: String
    var messages: [SimpleMessage]
    let createdAt: Date
    var updatedAt: Date
    /// Which execution backend owns this conversation: `"local"` (iCloud /
    /// on-device file store), or a remote backend's id (`"openclaw"` for the
    /// legacy single VM, otherwise a UUID string). Optional for backward
    /// compatibility: conversations written before this field existed decode as
    /// `nil` and are treated as local. See `backendKind`.
    var backend: String?

    init(id: String = UUID().uuidString,
         title: String,
         messages: [SimpleMessage] = [],
         createdAt: Date = Date(),
         updatedAt: Date = Date(),
         backend: String? = nil) {
        self.id = id
        self.title = title
        self.messages = messages
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.backend = backend
    }

    /// Display category of `backend`. A nil or `"local"` marker is `.local`;
    /// any other id is a remote backend (`.remote`). Pre-existing conversations
    /// (nil marker) behave exactly as before.
    var backendKind: ConversationBackend {
        (backend == nil || backend == ExecutionBackend.localID) ? .local : .remote
    }
}

struct SimpleMessage: Codable {
    let id: String
    let role: String
    let content: String
    let name: String?
    let functionName: String?
    let functionArguments: String?
    /// JSON-encoded array of every tool call on an assistant turn —
    /// `[{name, arguments, callId}]`. Drives the "Used N tools" disclosure on
    /// reload. The legacy singular `functionName`/`functionArguments` pair is
    /// still written for back-compat; this carries the full set since a turn
    /// can emit multiple parallel calls. Optional, so old rows decode to nil.
    let functionCallsJSON: String?
    let actions: String?
    /// JSON-encoded `FileAttachment` (image or PDF). Nil for messages without
    /// a user-uploaded attachment. Stored as a string so it rides alongside
    /// the other serialized fields without forcing a Core Data type change.
    let fileAttachment: String?
    /// JSON-encoded `MapAttachment` (place pins). Nil unless MapsSkill ran
    /// for this turn. Persisted so the inline map embed survives relaunch.
    let mapAttachment: String?
    /// JSON-encoded `ImageAttachment` (inline generated image). Nil unless
    /// ImageSkill produced a bubble for this turn. Persisted so a finished
    /// image reloads from its saved PNG, and an in-flight placeholder survives
    /// an app kill (reload coerces a stale `.generating` to a retryable
    /// `.failed`).
    let imageAttachment: String?
    /// Which model produced the message — "GPT 5.5 Instant", "Apple LLM",
    /// etc. Optional for backward compatibility with NDJSON entries written
    /// before this field existed. When nil, callers default to whatever
    /// `MessageStruct.model` initializes to.
    let model: String?
    /// True when this message is a synthetic compaction summary generated by
    /// opportunistic context compaction. Optional for backward compatibility.
    let isCompactionSummary: Bool?
    /// Response time in seconds for this assistant turn, surfaced next to the
    /// model name (e.g. "… 2.6s"). For local inference this is the live TTFT; for
    /// OpenClaw turns it's the agent run's `durationMs`. Optional for backward
    /// compatibility and nil for user/older messages.
    let responseSeconds: TimeInterval?
    let createdAt: Date

    init(id: String = UUID().uuidString,
         role: String,
         content: String,
         name: String? = nil,
         functionName: String? = nil,
         functionArguments: String? = nil,
         functionCallsJSON: String? = nil,
         actions: String? = nil,
         fileAttachment: String? = nil,
         mapAttachment: String? = nil,
         imageAttachment: String? = nil,
         model: String? = nil,
         isCompactionSummary: Bool? = nil,
         responseSeconds: TimeInterval? = nil,
         createdAt: Date = Date()) {
        self.id = id
        self.role = role
        self.content = content
        self.name = name
        self.functionName = functionName
        self.functionArguments = functionArguments
        self.functionCallsJSON = functionCallsJSON
        self.actions = actions
        self.fileAttachment = fileAttachment
        self.mapAttachment = mapAttachment
        self.imageAttachment = imageAttachment
        self.model = model
        self.isCompactionSummary = isCompactionSummary
        self.responseSeconds = responseSeconds
        self.createdAt = createdAt
    }
}

// MARK: - Simple Conversation Manager
//
// Public facade. Storage lives in `ConversationFileStore` — one NDJSON file
// per conversation under iCloud.com.bhat.LoopIOS/Documents/messages/, so iPhone
// and Mac stay in sync via iCloud Drive.
//
// "Current conversation" is no longer a per-device pointer in UserDefaults.
// `loadLastConversation()` instead returns the *most-recently-updated*
// conversation in the store — both iPhone and Mac open onto the same one,
// which is what users expect when bouncing between devices.

class SimpleConversationManager {
    static let shared = SimpleConversationManager()

    /// Fans reads across the local + remote backend stores and routes writes to
    /// whichever backend owns a conversation. New conversations are created in
    /// the active backend (local unless a remote is selected, configured, and
    /// validated). Existing conversations stay visible and on their own backend.
    let router = ConversationStoreRouter(
        local: ConversationFileStore.shared,
        activeRemoteID: { ExecutionBackendStore.shared.activeRemoteBackendID }
    )

    /// One conversation store per remote backend id, kept in sync with
    /// `ExecutionBackendStore`. Reused across rebuilds so a backend's in-memory
    /// cache/mirror survives edits to its settings.
    private var remoteStores: [String: OpenClawConversationStore] = [:]

    private init() {
        rebuildRemoteStores()
        NotificationCenter.default.addObserver(
            forName: ExecutionBackendStore.didChangeNotification,
            object: nil, queue: .main) { [weak self] _ in
                self?.rebuildRemoteStores()
            }
    }

    /// Create/update/remove the per-backend remote stores to match the current
    /// list of remote backends, then hand them to the router.
    private func rebuildRemoteStores() {
        let backends = ExecutionBackendStore.shared.remoteBackends
        var next: [String: OpenClawConversationStore] = [:]
        for backend in backends {
            if let existing = remoteStores[backend.id] {
                existing.updateConfig(backend.config)
                next[backend.id] = existing
            } else {
                next[backend.id] = OpenClawConversationStore(
                    backendID: backend.id, config: backend.config)
            }
        }
        remoteStores = next
        router.setRemotes(next)
    }

    /// The remote conversation store for a backend id, if one exists. Exposed for
    /// the background message poller, which drives each backend's session list +
    /// transcript reads through its store.
    func remoteStore(for backendID: String) -> OpenClawConversationStore? {
        remoteStores[backendID]
    }

    // MARK: - Current Conversation

    private var _currentConversation: SimpleConversation?
    var currentConversation: SimpleConversation? {
        get { return _currentConversation }
        set {
            let prevId = _currentConversation?.id
            _currentConversation = newValue
            // Post a notification when the *id* changes — re-assigning the
            // same conversation (e.g. after a save that refreshed the
            // snapshot) shouldn't churn observers. Surfaces are listening
            // to this to follow tab switches (Mac terminal pill, etc).
            if prevId != newValue?.id {
                NotificationCenter.default.post(
                    name: .activeConversationDidChange,
                    object: nil,
                    userInfo: ["conversationId": newValue?.id as Any]
                )
            }
        }
    }

    // MARK: - Conversation Operations

    func getAllConversations() -> [SimpleConversation] {
        return router.allConversations()
    }

    func getConversation(by id: String) -> SimpleConversation? {
        return router.conversation(id: id)
    }

    func createConversation(title: String = "New Conversation") -> SimpleConversation {
        return router.createConversation(title: title)
    }

    func saveConversation(_ conversation: SimpleConversation) {
        router.saveConversation(conversation)
        if currentConversation?.id == conversation.id {
            _currentConversation = conversation
        }
    }

    func deleteConversation(_ conversation: SimpleConversation) {
        router.deleteConversation(id: conversation.id)
        if currentConversation?.id == conversation.id {
            currentConversation = nil
        }
    }

    // MARK: - Message Operations

    func addMessage(_ messageStruct: MessageStruct, to conversation: SimpleConversation) {
        let simpleMessage = makeSimpleMessage(from: messageStruct, createdAt: Date())
        router.addMessage(simpleMessage, toConversation: conversation.id)

        // Refresh local snapshot of the current conversation so callers see the
        // appended message immediately without re-fetching.
        let refreshed = router.conversation(id: conversation.id)
        if currentConversation?.id == conversation.id, let fresh = refreshed {
            _currentConversation = fresh
        }

        // Conversation-title auto-generation. Fires at the first real
        // exchange (count == 2) so the placeholder "Chat 11/3, 4:02 PM"
        // gets replaced quickly, then every 5 messages after to refresh
        // the title as the topic drifts. Counted off user+assistant
        // messages only — function calls/results and system seeds don't
        // bump the milestone. ConversationTitleService dedupes by
        // conversationId so two rapid `addMessage` calls inside the
        // same milestone window won't double-fire.
        if let fresh = refreshed {
            let exchangeCount = fresh.messages.filter {
                $0.role == "user" || $0.role == "assistant"
            }.count
            if ConversationTitleService.shouldTrigger(forUserAssistantCount: exchangeCount) {
                ConversationTitleService.shared.regenerateFromPersisted(conversationId: conversation.id)
            }
        }
    }

    /// Re-persist an already-stored message in place — used when a message's
    /// attachment transitions after it was first written (e.g. an image flips
    /// from `.generating` to `.ready`/`.failed`). Preserves the original
    /// `createdAt` so message order is unchanged. No-op if the message isn't
    /// in the conversation yet (the first write should go through `addMessage`).
    func updateMessage(_ messageStruct: MessageStruct, in conversation: SimpleConversation) {
        let createdAt = router.messages(forConversation: conversation.id)
            .first { $0.id == messageStruct.id }?
            .createdAt ?? Date()
        let simpleMessage = makeSimpleMessage(from: messageStruct, createdAt: createdAt)
        router.updateMessage(simpleMessage, inConversation: conversation.id)
        if currentConversation?.id == conversation.id,
           let refreshed = router.conversation(id: conversation.id) {
            _currentConversation = refreshed
        }
    }

    /// Serializes a `MessageStruct` into the persisted `SimpleMessage` shape.
    /// Shared by `addMessage` (createdAt = now) and `updateMessage` (createdAt
    /// = the original, to keep ordering stable on rewrite).
    private func makeSimpleMessage(from messageStruct: MessageStruct, createdAt: Date) -> SimpleMessage {
        // Serialize function arguments (legacy singular pair — first call only).
        var functionArgumentsString: String? = nil
        if let function = messageStruct.function {
            if let data = try? JSONSerialization.data(withJSONObject: function.arguments),
               let string = String(data: data, encoding: .utf8) {
                functionArgumentsString = string
            }
        }

        // Serialize the full tool-call array so the "Used N tools" disclosure
        // can be rebuilt on reload, including turns with multiple parallel
        // calls that the singular pair above can't represent.
        var functionCallsString: String? = nil
        if !messageStruct.functions.isEmpty {
            let payload: [[String: Any]] = messageStruct.functions.map { call in
                var entry: [String: Any] = ["name": call.name, "arguments": call.arguments]
                if let callId = call.callId { entry["callId"] = callId }
                return entry
            }
            if let data = try? JSONSerialization.data(withJSONObject: payload),
               let string = String(data: data, encoding: .utf8) {
                functionCallsString = string
            }
        }

        // Serialize actions
        var actionsString: String? = nil
        if !messageStruct.actions.isEmpty {
            let actionStrings = messageStruct.actions.map { action in
                switch action {
                case .upload_driver_id:
                    return "upload_driver_id"
                }
            }
            if let data = try? JSONSerialization.data(withJSONObject: actionStrings),
               let string = String(data: data, encoding: .utf8) {
                actionsString = string
            }
        }

        // Serialize user-uploaded file attachment, if any. The encoder writes
        // URLs as plain strings — durable across launches since attachments
        // live in the workspace.
        var fileAttachmentString: String? = nil
        if let attachment = messageStruct.fileAttachment {
            if let data = try? JSONEncoder().encode(attachment),
               let string = String(data: data, encoding: .utf8) {
                fileAttachmentString = string
            }
        }

        // Serialize map embed (place pins) so it survives relaunch / sync.
        var mapAttachmentString: String? = nil
        if let attachment = messageStruct.mapAttachment {
            if let data = try? JSONEncoder().encode(attachment),
               let string = String(data: data, encoding: .utf8) {
                mapAttachmentString = string
            }
        }

        // Serialize inline generated image so the bubble survives relaunch:
        // a finished image reloads from its saved PNG; an interrupted one is
        // reconciled to a retryable failure by the host's cold-launch sweep.
        var imageAttachmentString: String? = nil
        if let attachment = messageStruct.imageAttachment {
            if let data = try? JSONEncoder().encode(attachment),
               let string = String(data: data, encoding: .utf8) {
                imageAttachmentString = string
            }
        }

        return SimpleMessage(
            id: messageStruct.id,
            role: messageStruct.role,
            content: messageStruct.content,
            name: messageStruct.name,
            functionName: messageStruct.function?.name,
            functionArguments: functionArgumentsString,
            functionCallsJSON: functionCallsString,
            actions: actionsString,
            fileAttachment: fileAttachmentString,
            mapAttachment: mapAttachmentString,
            imageAttachment: imageAttachmentString,
            // Persist model attribution so reload paths can show the same
            // "Apple LLM" / "GPT 5.5 Instant" badge that the live append
            // path renders. Only meaningful for assistant turns. User turns
            // reuse this column to carry the dictation byline ("Deepgram STT"/"Apple STT"),
            // which is otherwise unused for the user side.
            model: messageStruct.role == "assistant" ? messageStruct.model : messageStruct.sttEngine,
            isCompactionSummary: messageStruct.isCompactionSummary ? true : nil,
            responseSeconds: messageStruct.role == "assistant" ? messageStruct.ttft : nil,
            createdAt: createdAt
        )
    }

    func getMessages(for conversation: SimpleConversation) -> [SimpleMessage] {
        return router.messages(forConversation: conversation.id)
    }

    /// Poll a single conversation's file from its remote VM (the lightweight
    /// single-file fetch, not a full directory refresh) and merge any new lines
    /// into the cache. Used while a VM-side agent writes its reply so the chat
    /// can render the assistant turn as it lands. `completion` runs on the main
    /// queue with `true` when the VM was reachable. No-op (`completion(false)`)
    /// for local conversations, which never poll.
    func refreshRemoteConversation(id: String, completion: ((Bool) -> Void)? = nil) {
        let store = remoteStores.values.first(where: { $0.conversation(id: id) != nil })
            ?? ExecutionBackendStore.shared.activeRemoteBackendID.flatMap { remoteStores[$0] }
        guard let store = store else { completion?(false); return }
        store.refreshConversation(id: id) { [weak self] reachable in
            if let self = self, self.currentConversation?.id == id,
               let refreshed = self.router.conversation(id: id) {
                self._currentConversation = refreshed
            }
            completion?(reachable)
        }
    }

    /// Drive a remote (OpenClaw) user turn over the warm Gateway WebSocket,
    /// streaming the reply. `onDelta` gets incremental text and `completion` the
    /// final persisted assistant message — both on the main queue. The user
    /// message must already be persisted (via `addMessage`). Routes to the store
    /// that owns the conversation (falling back to the active remote backend).
    func sendRemoteStreaming(text: String, attachment: FileAttachment? = nil, conversationId id: String,
                             onDelta: @escaping (String) -> Void,
                             onToolCall: @escaping (FunctionCallStruct) -> Void = { _ in },
                             completion: @escaping (Result<MessageStruct, Error>) -> Void) {
        let store = remoteStores.values.first(where: { $0.conversation(id: id) != nil })
            ?? ExecutionBackendStore.shared.activeRemoteBackendID.flatMap { remoteStores[$0] }
        guard let store = store else {
            completion(.failure(OpenClawGatewayError.notConnected)); return
        }
        let toolCall: (String, String?, [String: Any]) -> Void = { name, callId, input in
            onToolCall(FunctionCallStruct(name: name, arguments: input, callId: callId, conversationId: id))
        }
        store.sendStreaming(text: text, attachment: attachment, conversationId: id, onDelta: onDelta, onToolCall: toolCall) { [weak self] result in
            switch result {
            case .success(let msg):
                if let self = self, self.currentConversation?.id == id,
                   let refreshed = self.router.conversation(id: id) {
                    self._currentConversation = refreshed
                }
                let ms = self?.messageStruct(from: msg) ?? MessageStruct(role: "assistant", content: msg.content)
                completion(.success(ms))
            case .failure(let e):
                completion(.failure(e))
            }
        }
    }

    /// Remove a single message by id from a conversation. Used by Mac escape
    /// cancellation; mirrors `addMessage` in keeping the in-memory snapshot of
    /// `currentConversation` consistent with the store.
    func removeMessage(id messageId: String, from conversation: SimpleConversation) {
        router.removeMessage(id: messageId, fromConversation: conversation.id)
        if currentConversation?.id == conversation.id,
           let refreshed = router.conversation(id: conversation.id) {
            _currentConversation = refreshed
        }
    }

    // MARK: - App Lifecycle

    /// On launch, both iPhone and Mac open the most-recently-updated
    /// conversation — whichever device touched something last "wins". The
    /// user can still navigate to older conversations via the sidebar after
    /// launch; that selection is purely a runtime state and isn't persisted.
    ///
    /// May transiently return nil during the brief window before
    /// `ConversationFileStore` finishes its pass-1 meta enumeration. Callers
    /// should treat nil as "no conversation available yet" and fall back to
    /// `createConversation(...)` so the user isn't blocked.
    func loadLastConversation() -> SimpleConversation? {
        let conversation = router.mostRecentlyUpdatedConversation()
        _currentConversation = conversation
        return conversation
    }

    func createDefaultConversationIfNeeded() -> SimpleConversation {
        if let existing = currentConversation {
            return existing
        }
        if let mostRecent = router.mostRecentlyUpdatedConversation() {
            currentConversation = mostRecent
            return mostRecent
        }
        let conversation = createConversation(title: "General Questions")
        currentConversation = conversation
        return conversation
    }

    func clearCurrentConversation() {
        currentConversation = nil
    }

    // MARK: - Conversion Methods

    func messageStruct(from simpleMessage: SimpleMessage) -> MessageStruct {
        var messageStruct = MessageStruct(
            id: simpleMessage.id,
            role: simpleMessage.role,
            content: simpleMessage.content,
            name: simpleMessage.name,
            timestamp: simpleMessage.createdAt
        )
        // Old NDJSON rows have no `model` field — leave the MessageStruct
        // default in place for those so behavior is unchanged for old chats.
        // User rows reuse this column for the dictation byline (see
        // `toSimpleMessage`), so route it back to `sttEngine` there.
        if let stored = simpleMessage.model, !stored.isEmpty {
            if simpleMessage.role == "user" {
                messageStruct.sttEngine = stored
            } else {
                messageStruct.model = stored
            }
        }
        // Persisted response time renders next to the model name (e.g. "… 2.6s").
        if let seconds = simpleMessage.responseSeconds {
            messageStruct.ttft = seconds
        }

        // Prefer the full tool-call array (covers multi-call turns); fall back
        // to the legacy singular pair for rows written before that field.
        if let callsString = simpleMessage.functionCallsJSON,
           let callsData = callsString.data(using: .utf8),
           let rawCalls = try? JSONSerialization.jsonObject(with: callsData) as? [[String: Any]] {
            messageStruct.functions = rawCalls.compactMap { entry in
                guard let name = entry["name"] as? String else { return nil }
                let arguments = entry["arguments"] as? [String: Any] ?? [:]
                return FunctionCallStruct(name: name, arguments: arguments, callId: entry["callId"] as? String)
            }
        } else if let functionName = simpleMessage.functionName,
           let argumentsString = simpleMessage.functionArguments,
           let argumentsData = argumentsString.data(using: .utf8),
           let arguments = try? JSONSerialization.jsonObject(with: argumentsData) as? [String: Any] {
            messageStruct.function = FunctionCallStruct(name: functionName, arguments: arguments)
        }

        if let actionsString = simpleMessage.actions,
           let actionsData = actionsString.data(using: .utf8),
           let actionsArray = try? JSONSerialization.jsonObject(with: actionsData) as? [String] {
            messageStruct.actions = actionsArray.compactMap { actionString in
                switch actionString {
                case "upload_driver_id":
                    return .upload_driver_id
                default:
                    return nil
                }
            }
        }

        if let attachmentString = simpleMessage.fileAttachment,
           let attachmentData = attachmentString.data(using: .utf8),
           let attachment = try? JSONDecoder().decode(FileAttachment.self, from: attachmentData) {
            messageStruct.fileAttachment = attachment
        }

        if let mapString = simpleMessage.mapAttachment,
           let mapData = mapString.data(using: .utf8),
           let map = try? JSONDecoder().decode(MapAttachment.self, from: mapData) {
            messageStruct.mapAttachment = map
        }

        // Decode the persisted image as-is. A `.generating` that's actually
        // stale (its job died with a previous process) is reconciled to a
        // retryable `.failed` by the host's cold-launch sweep — which knows
        // whether a live job still exists, so we don't false-fail an image
        // that's mid-flight when the user switches conversations and back.
        if let imageString = simpleMessage.imageAttachment,
           let imageData = imageString.data(using: .utf8),
           let image = try? JSONDecoder().decode(ImageAttachment.self, from: imageData) {
            messageStruct.imageAttachment = image
        }

        if simpleMessage.isCompactionSummary == true {
            messageStruct.isCompactionSummary = true
        }

        return messageStruct
    }

    func conversationStruct(from simpleConversation: SimpleConversation) -> Conversation {
        let id = simpleConversation.id
        let hasAgents = SubAgentManager.shared.aggregateLiveCount(for: id) > 0
        let hasActiveRequest = ActiveRequestTracker.shared.isActive(for: id)
        return Conversation(
            id: id,
            title: simpleConversation.title,
            lastMessage: simpleConversation.messages.last?.content ?? "",
            timestamp: simpleConversation.updatedAt,
            isRunning: hasAgents || hasActiveRequest,
            backend: simpleConversation.backendKind
        )
    }
}
